# Generated by Django 3.2.4 on 2022-05-20 02:05

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('dtgerado', models.DateTimeField(auto_now_add=True)),
                ('dtatualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.IntegerField(null=True)),
                ('cor', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'demanda',
            },
        ),
        migrations.CreateModel(
            name='Fila_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=250)),
                ('assunto', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(null=True)),
                ('anexo', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'fila_email',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tipo', models.IntegerField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'setor',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cor', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'tipo',
            },
        ),
        migrations.CreateModel(
            name='TipoAndamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('tipo', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'tipo_andamento',
            },
        ),
        migrations.CreateModel(
            name='TipoHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('faturavel', models.CharField(max_length=3)),
                ('classe', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'tipo_hora',
            },
        ),
        migrations.CreateModel(
            name='UsuarioDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1, null=True)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.demanda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_demanda',
            },
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtgerado', models.DateTimeField(auto_now_add=True)),
                ('dtinicio', models.DateTimeField(null=True)),
                ('dtfim', models.DateTimeField(null=True)),
                ('ano', models.IntegerField()),
                ('horas', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
            ],
            options={
                'db_table': 'pacote',
            },
        ),
        migrations.CreateModel(
            name='GrupoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grupo_usuario',
            },
        ),
        migrations.AddField(
            model_name='demanda',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.setor'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.status'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipo'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Andamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', ckeditor_uploader.fields.RichTextUploadingField()),
                ('dtgerado', models.DateTimeField(auto_now_add=True, null=True)),
                ('dtatualizado', models.DateTimeField(auto_now=True)),
                ('hora', models.CharField(max_length=5, null=True)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.demanda')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoandamento')),
                ('tipo_hora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipohora')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'andamento',
            },
        ),
    ]
